name: Run Playwright Bot

on:
  workflow_dispatch: # هذا السطر يسمح لك بتشغيل السكريبت يدوياً بضغطة زر متى شئت

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install chromium

    - name: Install Virtual Display (xvfb)
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    - name: Run Bot Script
      run: |
        # أداة xvfb-run تهم للمتصفح أن هناك شاشة حقيقية مقاسها 1280x720 لكي لا يعطي أخطاء
        xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python main.py
